-- ============================================
-- CATÁLOGO DE AVATARES
-- ============================================

-- Catálogo de avatares disponíveis no jogo
CREATE TABLE IF NOT EXISTS public.avatares (
    id_avatar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    caminho_imagem VARCHAR(255) NOT NULL,
    descricao TEXT,
    modulo_desbloqueio INTEGER DEFAULT 1,
    eh_padrao BOOLEAN DEFAULT false
);

-- Avatares que o usuário já desbloqueou
CREATE TABLE IF NOT EXISTS public.usuario_avatares (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_avatar INTEGER NOT NULL,
    equipado BOOLEAN DEFAULT false,
    desbloqueado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (id_avatar) REFERENCES public.avatares(id_avatar) ON DELETE CASCADE,
    UNIQUE(id_usuario, id_avatar)
);

-- Índice para garantir apenas 1 avatar equipado por usuário
CREATE UNIQUE INDEX IF NOT EXISTS idx_avatar_equipado
    ON public.usuario_avatares (id_usuario)
    WHERE equipado = true;

-- ============================================
-- INSERIR AVATARES NO CATÁLOGO (SEM DUPLICATAS)
-- ============================================
-- A mágica está no NOT EXISTS: ele "lê" o banco e só insere a linha 
-- se não houver nenhum avatar cadastrado com aquele nome.
INSERT INTO public.avatares (nome, caminho_imagem, descricao, modulo_desbloqueio, eh_padrao)
SELECT v.nome, v.caminho_imagem, v.descricao, v.modulo_desbloqueio, v.eh_padrao
FROM (
    VALUES
        ('Corvo', 'corvo.png', 'Avatar básico do companheiro do SM', 1, true),
        ('Alef', 'alef.png', 'Avatar do guerreiro da sprint', 2, false),
        ('Cauã', 'caua.png', 'Avatar do programador de poções', 3, false),
        ('Enzo', 'enzo.png', 'Avatar do enorme tanque magico', 4, false),
        ('Igor', 'igor.png', 'Avatar do mago das magias proíbidas', 5, false),
        ('Lorenzo', 'lorenzo.png', 'Avatar do arqueiro mestre das sprints', 6, false),
        ('Patrícia', 'patricia.png', 'Avatar da maga detentora da luz', 7, false),
        ('Renan', 'renan.png', 'Avatar do estudioso magico elétrico', 8, false),
        ('Thiago', 'thiago.png', 'Avatar do poderoso mago das linguagens', 9, false),
        ('Vitor', 'vitor.png', 'Avatar do grandioso bardo da conexão (e seu pet)', 10, false)
) AS v (nome, caminho_imagem, descricao, modulo_desbloqueio, eh_padrao)
WHERE NOT EXISTS (
    SELECT 1 FROM public.avatares a WHERE a.nome = v.nome
);

-- ============================================
-- DAR AVATAR PADRÃO AOS USUÁRIOS (SEM AVATAR)
-- ============================================

-- 1. Inserir na tabela usuario_avatares apenas se o usuário não tiver NENHUM avatar
INSERT INTO public.usuario_avatares (id_usuario, id_avatar, equipado)
SELECT u.id_usuario, a.id_avatar, true
FROM public.usuarios u
CROSS JOIN public.avatares a
WHERE a.eh_padrao = true
AND NOT EXISTS (
    SELECT 1 FROM public.usuario_avatares ua 
    WHERE ua.id_usuario = u.id_usuario
)
ON CONFLICT (id_usuario, id_avatar) DO UPDATE SET equipado = true;

-- 2. Sincronizar com a coluna avatar da tabela usuarios
UPDATE public.usuarios u
SET avatar = a.caminho_imagem
FROM public.usuario_avatares ua
JOIN public.avatares a ON ua.id_avatar = a.id_avatar
WHERE u.id_usuario = ua.id_usuario
AND ua.equipado = true;

-- 3. Garante que ninguém fique sem avatar (fallback para corvo.png)
UPDATE public.usuarios
SET avatar = 'corvo.png'
WHERE avatar IS NULL OR avatar = 'default.png';