-- Catálogo de avatares disponíveis no jogo
CREATE TABLE IF NOT EXISTS public.avatares (
    id_avatar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    caminho_imagem VARCHAR(255) NOT NULL,
    descricao TEXT,
    modulo_desbloqueio INTEGER DEFAULT 1,
    eh_padrao BOOLEAN DEFAULT false
);

-- Avatares que o usuário já desbloqueou
CREATE TABLE IF NOT EXISTS public.usuario_avatares (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_avatar INTEGER NOT NULL,
    equipado BOOLEAN DEFAULT false,
    desbloqueado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (id_avatar) REFERENCES public.avatares(id_avatar) ON DELETE CASCADE,
    UNIQUE(id_usuario, id_avatar)
);

-- Índice para garantir apenas 1 avatar equipado por usuário
CREATE UNIQUE INDEX IF NOT EXISTS idx_avatar_equipado
    ON public.usuario_avatares (id_usuario)
    WHERE equipado = true;

-- Inserir avatares padrão (ignora se já existir)
INSERT INTO public.avatares (nome, caminho_imagem, descricao, modulo_desbloqueio, eh_padrao) VALUES
    ('Guerreiro', 'guerreiro.png', 'Avatar básico do guerreiro', 1, true),
    ('Mago', 'mago.png', 'Avatar do mago arcano', 2, false),
    ('Arqueiro', 'arqueiro.png', 'Avatar do arqueiro élfico', 3, false),
    ('Ladino', 'ladino.png', 'Avatar do ladino sombrio', 4, false),
    ('Paladino', 'paladino.png', 'Avatar do paladino sagrado', 5, false)
ON CONFLICT (id_avatar) DO NOTHING;