-- Adicionar colunas de dados da conta (se não existirem)
ALTER TABLE public.usuarios 
ADD COLUMN IF NOT EXISTS data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.usuarios 
ADD COLUMN IF NOT EXISTS ultimo_acesso TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.usuarios 
ADD COLUMN IF NOT EXISTS tempo_total INTERVAL DEFAULT '0 seconds';

-- Tabela para registrar tempo de sessão
CREATE TABLE IF NOT EXISTS public.sessoes_usuario (
    id_sessao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    tempo_inicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tempo_fim TIMESTAMP,
    duracao INTERVAL,
    FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE
);

-- Índice para performance (apenas na tabela nova)
CREATE INDEX IF NOT EXISTS idx_sessoes_usuario ON public.sessoes_usuario(id_usuario);

-- REMOVIDO: Índices opcionais que podem falhar se as colunas não existirem
-- CREATE INDEX IF NOT EXISTS idx_respostas_usuario ON public.respostas(id_usuario);
-- CREATE INDEX IF NOT EXISTS idx_exames_usuario ON public.exames(id_usuario);