"use strict";

const assert = require("assert");
const fs = require("fs");

const ejs = fs.readFileSync("public/pages/capitulo4.ejs", "utf8");
const css = fs.readFileSync("public/assets/css/capitulo4.css", "utf8");
const js = fs.readFileSync("public/assets/js/capitulo4.js", "utf8");

assert.match(ejs, /id="cena-forja"/);
assert.match(ejs, /A Porta da Definition of Done/);
assert.match(ejs, /Somente incrementos prontos atravessam/);
assert.match(ejs, /Definition of Done/);
assert.match(ejs, /DoD . o acordo que define quando\s+um incremento pode ser considerado realmente pronto/);
assert.match(ejs, /qualidade do incremento/);
assert.match(ejs, /qualidade . responsabilidade compartilhada pelo time/);
assert.match(ejs, /Pronto . um acordo vis.vel, n.o uma sensa..o/);
assert.match(ejs, /class="dod-forge"/);
assert.match(ejs, /class="dod-door"/);
assert.doesNotMatch(ejs, /porta-dod-pixel/);
assert.match(ejs, /data-dod-criterion="codigo"/);
assert.match(ejs, /data-dod-criterion="testes"/);
assert.match(ejs, /data-dod-criterion="criterios"/);
assert.match(ejs, /data-dod-criterion="revisao"/);
assert.match(ejs, /data-dod-criterion="defeitos"/);
assert.match(ejs, /id="btnValidarDod"/);
assert.strictEqual((ejs.match(/data-dod-check/g) || []).length, 5);
assert.match(ejs, /C.digo integrado/);
assert.match(ejs, /Testes executados/);
assert.match(ejs, /Crit.rios de aceita..o atendidos/);
assert.match(ejs, /Revis.o realizada/);
assert.match(ejs, /Sem defeitos cr.ticos conhecidos/);

assert.match(css, /\.dod-forge/);
assert.match(css, /\.dod-door/);
assert.match(css, /porta-dod-frame-pixel\.png/);
assert.match(css, /\.dod-door::after/);
assert.match(css, /\.dod-criterion--lit/);
assert.match(css, /\.dod-criterion--missing/);
assert.doesNotMatch(css, /\.dod-door--open/);
assert.doesNotMatch(css, /\.dod-door--opening/);
assert.match(css, /\.dod-checklist/);
assert.match(css, /\.dod-forge--complete/);
assert.match(css, /\.dod-button--ready/);
assert.match(css, /\.story-block\.is-unlocking/);
assert.match(css, /\.dod-status/);

assert.match(js, /function configurarDod/);
assert.match(js, /btnValidarDod/);
assert.match(js, /data-dod-check/);
assert.match(js, /atualizarCriteriosDod/);
assert.match(js, /atualizarBotaoDod/);
assert.match(js, /destacarCriteriosDodFaltantes/);
assert.match(js, /Faltam/);
assert.match(js, /Liberando pr.ximo trecho/);
assert.match(js, /scrollTo/);
assert.match(js, /dod-criterion--lit/);
assert.match(js, /dod-criterion--missing/);
assert.doesNotMatch(js, /dod-door--open/);
assert.doesNotMatch(js, /dod-door--opening/);
assert.match(js, /dod-forge--complete/);
